# Generated by Django 2.1.1 on 2018-10-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('search_date', models.DateField(auto_now=True)),
                ('google_response', models.TextField(max_length=1000)),
                ('weather_response', models.TextField(max_length=1000)),
            ],
        ),
    ]
