# Generated by Django 2.1.1 on 2018-10-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.CharField(max_length=200)),
                ('End', models.CharField(max_length=200)),
                ('Mode', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('google_response', models.TextField(max_length=1000)),
                ('weather_response', models.TextField(max_length=1000)),
            ],
        ),
    ]
